### ISSUE TITLE
Latest commit 95c95f3  on Nov 25, 2016 - is this repo not very alive?

### ISSUE THREAD

**Issue by rusefi** [ashabelnikov/secu3app#10]
Can you please clarify the status of this repo?

"Latest commit 95c95f3  on Nov 25, 2016" is a couple years old now?

**Comment by ashabelnikov** [comment]
It is alive and it will be updated in the future (not now). I don't understand why you interested in it.

**Comment by legath** [comment]
Not only Andrew interested..

**Comment by rusefi** [comment]
It has been many months. I believe it's misleading to keep calling secu3 "open source" while not publishing fresh source codes :)
