### ISSUE TITLE
19-01-2017 changes?

### ISSUE THREAD

**Issue by rusefi** [ashabelnikov/secu3app#9]
http://secu-3.org/forum/viewtopic.php?f=64&t=1047 mentions 19-01-2017 release but this repo is not updated since 2016. Is this firmware closed source now?

Sorry to hear about the clones :(

**Comment by ashabelnikov** [comment]
http://secu-3.org/forum/viewtopic.php?f=7&t=1026
I tired to catch offenders on the internet.

**Comment by rusefi** [comment]
But your GPL firmware license actually allows users to sell, as long as they mention your copyright and do not create closed source derivatives, does not it?

**Comment by ashabelnikov** [comment]
They don't mentioned me and my copyright. They advertised it as own developments, trying to appropriate my IP to software and hardware.

**Comment by rusefi** [comment]
Are we talking only about S-ECU or are there any others?

Yes not mentioning your copyright is definitely an infringement. I was just saying that technically they could have chosen to sell it in a legit way. They did and you should try to shut them down, you have a very simple to prove complaint. I believe it should be pretty easy to shut down their website.

**Comment by ashabelnikov** [comment]
Yes, I caught them on several sites (including speeduino, opelgt).

**Comment by rusefi** [comment]
Have you reported his threads to opelgt admins? I've actually just registered there and reported three of his threads - about three hours ago. Will let you know I get any response.

Have you reported him on speeduino? C'mon, speeduino would delete his stuff for sure.

**Comment by rusefi** [comment]
PS; worst case scenario my report on opelgt would be ignored simply because I am not the copyright owner. Do you have an account on opelgt?

**Comment by rusefi** [comment]
Have you seen http://www.opelgt.com/forums/fuel-injection-mods/86314-s-ecu-very-preliminary-user-manual.html ? I suspect our hero is moving to speeduino.

**Comment by rusefi** [comment]
The offender is no longer alive.
